modLoader = "javafml"
loaderVersion = "[@FORGE_LOADER_MAJOR@,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "@MODID@"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.@MODID@]]
modId = "forge"
mandatory = true
versionRange = "[@FORGE_LOADER_MAJOR@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.@MODID@]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.@MODID@]]
modId = "architectury"
mandatory = true
versionRange = "[@ARCHITECTURY_API@,)"
ordering = "AFTER"
side = "BOTH"